server:
  port: 9010

logging:
  level:
    root: info
    com.ruifucredit.cloud.commodity: debug

spring:
  application:
    name: commodity-service
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@ip:port/name
    username: username
    password: password

eureka:
  instance:
    appname: commodity-service
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
